# Generated by Django 4.1.5 on 2023-01-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(max_length=250)),
                ('nome', models.CharField(blank=True, max_length=70, null=True)),
                ('data_input', models.DateTimeField(auto_now=True)),
                ('rave', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'Mensagens',
            },
        ),
    ]
